const express = require("express");
const session = require("express-session");
const bodyParser = require("body-parser");
const cors = require("cors");
const path = require("path");
const swaggerUi = require("swagger-ui-express");
const swaggerFile = require("./swagger-output.json"); // Generated by swagger-autogen

const authRoutes = require("./routes/auth");
const feedbackRoutes = require("./routes/feedback");
const inquiryRoutes = require("./routes/inquiries");

const app = express();
const PORT = 3000;

// === Middleware ===
app.use(cors());
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));
app.use(session({
    secret: "eventease_secret",
    resave: false,
    saveUninitialized: false
}));
app.use(express.static(path.join(__dirname, "public")));

// === API Routes ===
app.use("/api/auth", authRoutes);
app.use("/api/feedback", feedbackRoutes);
app.use("/api/inquiries", inquiryRoutes);

// === Swagger UI (based on generated JSON) ===
app.use("/api-docs", swaggerUi.serve, swaggerUi.setup(swaggerFile));

// === Main Entry ===
app.get("/", (req, res) => {
    res.sendFile(path.join(__dirname, "public", "index.html"));
});

// === Start Server ===
app.listen(PORT, () => {
    console.log(`🚀 Server running at http://localhost:${PORT}`);
    console.log(`📚 Swagger UI: http://localhost:${PORT}/api-docs`);
});
